var allRecipes = {
  broccoliCheddar : {
  name: "Broccoli Cheddar Soup",
  servings: "4 to 6",
  cookTime: "45 minutes, including prep",
  ingredients: [
    "4 tablespoons unsalted butter",
    "1 small onion, chopped small",
    "1 garlic clove, minced",
    "1/4 cup all-purpose flour",
    "1 cup half-and-half",
    "4 cups low-sodium vegetable broth",
    "1 bay leaf",
    "4 cups broccoli florets and stems, chopped small",
    "1 large carrot or 2 slim ones, chopped tiny",
    "2 1/2 cups coarsely grated sharp cheddar cheese, plus a pinch extra for garnish",
    "Kosher salt and freshly ground pepper",
  ],
  directions: [
    "Melt the butter in a large, heavy pot over medium heat. Add the onion and garlic and cook until tender, about 3 to 5 minutes. Stir in the flour and cook until golden, 3 to 4 minutes, then gradually whisk in the half-and-half until smooth. Add the chicken broth, bay leaf, salt and pepper and bring to a simmer. Reduce the heat to medium-low and cook, uncovered, stirring occasionally, until slightly thickened, about 10 minutes.",
    "Add the broccoli and carrot to the broth mixture and simmer until tender, about 15 to 20 minutes. Discard the bay leaf and adjust seasoning if needed, but err on the cautious side with the salt because the cheese will add a bit. Puree the soup to your desired texture. Back on the stove, add cheese and whisk until melted, about 1 minute.",
    "Serve in bowls, garnished with a pinch of cheese.",
  ],
  tags: [
    "freezer friendly",
    "fall",
    "winter",
    "broccoli",
    "cheddar",
    "soup",
  ],
  source: "http://smittenkitchen.com/blog/2015/09/broccoli-cheddar-soup/",
  },

  sangria: {
    name: "",
    servings: "",
    cookTime: "",
    ingredients: [
      "1.5 oz/40g peeled ginger root (about one 4 1/2-inch knob)",
      "2 tablespoons water",
      "1/3 cup sugar",
      "20 green cardamom pods",
      "2 1/4 cups red wine",
      "1 cup orange juice (or 3 to 4 oranges, juiced)",
      "1/2 cup plus 1 tablespoon sweet vermouth (such as Carpano Antica)",
    ],
    directions: [
      "To Make the Ginger-Cardamom Syrup: If using a juicer, juice ginger (yields will vary), then measure out 2 tablespoons fresh ginger juice and mix with water. Proceed to step 2. If using an immersion blender, chop ginger roughly, then add to blender jar with water and blend thoroughly. Strain through a fine-mesh strainer; mixture should yield 4 tablespoons ginger liquid.",
      "In a small saucepan, combine ginger liquid and sugar. Warm over medium heat, stirring until sugar dissolves, removing from heat as soon as sugar dissolves; do not let boil. Add cardamom pods, cover, and let cool. Refrigerate at least 2 and up to 10 hours.",
      "To Make the Sangria: Add wine, orange juice, and sweet vermouth to a pitcher. Strain Ginger-Cardamom Syrup into pitcher and stir to mix. Serve immediately or refrigerate up to 2 hours.",
    ],
    tags: [
      "summer",
      "sangria",
      "alcohol",
      "drinks",
    ],
    source: "http://www.seriouseats.com/recipes/2016/06/red-wine-sangria-ginger-cardamom-recipe.html",
  },

  hollandaise: {
    name: "Hollandaise Sauce",
    servings: "6",
    cookTime: "10 minutes",
    ingredients: [
      "3 egg yolks",
      "1/2 lemon, juiced",
      "1 tsp. cold water",
      "1/2 c. butter",
      "salt and pepper to taste",
    ],
    directions: [
      "In a small bowl, whisk together egg yolks, lemon juice, cold water, salt and pepper. Melt butter in a saucepan over low heat. Do not let the butter boil, or the sauce will separate and become chunky. Gradually whisk yolk mixture into butter. Continue whisking over low heat for 8 minutes, or until sauce is thickened. Serve immediately. If the sauce is separating, add a splash of very cold water and whisk quickly until smooth."
    ],
    tags: [
      "breakfast",
      "sauce",
      "hollandaise",
    ],
    source: "http://allrecipes.com/recipe/35995/classic-hollandaise-sauce/",
    },

  biscuits: {
    name: "Cacio e Pepe Biscuits",
    servings: "12",
    cookTime: "30 minutes",
    ingredients: [
      "2 3/4 cups all-purpose flour",
      "1/2 tsp. kosher salt",
      "1 tbsp. baking powder",
      "1 cup (2 sticks) unsalted butter, very cold",
      "1	cup grated Pecorino Romano cheese",
      "2 tbsp. freshly ground black pepper",
      "1 cup milk",
    ],
    directions: [
      "Preheat your oven to 425° F. Line two baking sheets with parchment paper.",
      "In a large bowl, whisk together the flour, salt, and baking powder. Cut in the cold butter using a fork or pastry cutter. The mixture should have pea-sized lumps.",
      " Stir in the grated cheese and black pepper with a fork and pour in the milk. Stir until the dough is a shaggy, wet mess. Once it mostly comes together, use your hands to fold in the dry bits that haven't been incorporated. You want to be very gentle and use your hands as little as possible. Focus on folding the dough over onto itself until it mostly comes together.",
      "Turn the dough out onto a lightly floured surface and pat it into a 1 1/2-inch-thick disc. Using a sharp biscuit cutter (or a round cookie cutter), cut out circles.",
      " Place the dough circles onto your prepared baking sheets. Sprinkle a generous amount of black pepper and grated cheese over the top of each biscuit. Bake for 10 to 12 minutes, or until just golden brown on the edges. Remove from the oven and let cool slightly.",
    ],
    tags: [
      "cacio e pepe",
      "biscuits",
      "breakfast",
      "dinner",
      "winter",
      "fall",
    ],
    source: "http://food52.com/recipes/41421-cacio-e-pepe-biscuits",
  },
  indianCauliflower: {
    name: "Indian Spiced Cauliflower and Potatoes",
    servings: "4",
    cookTime: "50 minutes",
    ingredients: [
      "1 head cauliflower, cut into 3/4-inch-wide florets",
      "1 1/4 lb potatoes, peeled and cut into 1/2-inch cubes",
      "5 tbsp. olive oil",
      "1/2 tsp. cumin seeds",
      "3/4 tsp. salt",
      "1 medium onion, finely chopped",
      "2 garlic cloves, finely chopped",
      "2 tsp. minced fresh jalapeño, including seeds",
      "2 tsp. minced peeled fresh ginger",
      "1 tsp. ground cumin",
      "1/2 tsp. ground coriander",
      "1/4 tsp. turmeric",
      "1/4 teaspoon cayenne",
      "1/2 cup water",
      "Accompaniment: lemon wedges",
    ],
    directions: [
      "Put oven rack in upper third of oven and place a shallow baking pan on rack. Preheat oven to 475°F.",
      "Toss cauliflower and potatoes together in a bowl with 3 tablespoons oil, cumin seeds, and1/4 teaspoon salt. Spread in hot baking pan and roast, stirring occasionally, until cauliflower is tender and browned in spots and potatoes are just tender, about 20 minutes.",
      "While vegetables are roasting, cook onion, garlic, jalapeño, and ginger in remaining 2 tablespoons oil in a 12-inch heavy skillet over moderate heat, stirring frequently, until very soft and beginning to turn golden, 8 to 10 minutes.",
      "Add ground cumin, coriander, turmeric, cayenne, and remaining 1/2 teaspoon salt and cook, stirring constantly, 2 minutes. Stir in water, scraping up any brown bits from bottom of skillet, then stir in roasted vegetables. Cook, covered, stirring occasionally, 5 minutes."
    ],
    source: " http://www.epicurious.com/recipes/food/views/indian-spiced-cauliflower-and-potatoes-109118",
    tags: [
      "indian",
      "cauliflower",
      "potatoes",
      "fall",
      "winter",
    ],
    home: '/',
  },
  mintJulep: {
    name: "Mint Juleps",
    servings: "1",
    cookTime: "7 minutes",
    ingredients: [
      "~7 fresh mint leaves, plus one for garnish",
      "2 shots Kentucky bourbon whiskey",
      "1.5 tsp. light brown sugar, or to taste",
      "2-3 ice cubes",
    ],
    directions: [
      "Tear any large mint leaves into pieces, then combine mint leaves and the sugar in an old-fashioned glass or metal julep cup. Muddle these together with a muddler or back of a spoon for approximately 1 minute so the leaves release their essential oils but are still green. Add the bourbon and serve, preferably after letting ingredients rest for 5 minutes.",
    ],
    source: "http://altonbrown.com/mint-julep/",
    tags: [
      "alcohol",
      "mint",
      "summer",
      "drinks",
    ],
    home: '/',
  },

  gazpacho: {
    name: "Gazpacho",
    servings: "6",
    cookTime: "30 minutes",
    ingredients: [
      "3 garlic cloves, or garlic paste",
      "2 onions, peeled",
      "1 cucumber, peeled and seeded",
      "1 red pepper, seeded",
      "2 1/4 lb ripe tomatoes (~12), seeded",
      "1 jalapeno, seeded",
      "1 1/4 oz white country-style bread (without crust)",
      "1/2 cup water",
      "1/3 cup olive oil, plus extra to serve",
      "2 tbsp sherry vinegar",
      "1 tbsp mayonnaise",
      "2 tbsp. minced fresh herbs (tarragon, thyme, or parsley)",
      "Juice of 1/2 lemon, or as needed",
      "1/4 tsp. salt, or as needed",
      "1/4 tsp. cayenne pepper, or as needed",
      "1 cup croutons",
      "1/2 cup thinly sliced chives or scallion greens",
    ],
    directions: [
      "Dice all vegetables and herbs and place in a blender. Add the bread, torn into pieces, then pour over the water. Process everything together until the desired consistency. Add the oil, vinegar, and mayonnaise, then whisk or blend the soup until smooth and creamy. Season with salt and pepper. Chill in the fridge before serving (at least 2 hours). Serve the gazpacho in soup bowls with croutons, plus an extra drizzle of olive oil."
    ],
    source: "http://www.epicurious.com/recipes/food/views/gazpacho-357151",
    tags: [
      "summer",
      "soup",
      "gazpacho",
    ],
    home: '/',
  },

  oldFashioned: {
    name: "Old Fashioned",
    servings: "1",
    cookTime: "5 minutes",
    ingredients: [
      "1/2 tsp. sugar (or 1 sugar cube)",
      "3 drops bitters",
      "2 oz. rye whiskey",
      "1 half-dollar sized slice orange peel, including pith",
    ],
    directions: [
      "Place the sugar cube (or 1/2 teaspoon loose sugar) in an Old-Fashioned glass. Wet it down with 2 or 3 dashes of bitters and a short splash of water or club soda. Crush the sugar with a wooden muddler, chopstick, strong spoon, lipstick, cartridge case, whatever. Rotate the glass so that the sugar grains and bitters give it a lining. Add a large ice cube. Pour in the rye (or bourbon). Serve with a stirring rod."
    ],
    source: "http://www.esquire.com/food-drink/drinks/recipes/a3880/old-fashioned-drink-recipe/",
    tags: [
      "all-season",
      "alcohol",
      "whiskey",
    ],
    home: '/',
  },

  indianLentilsCabbage: {
    name: "Indian Lentils and Cabbage",
    servings: "4 to 6",
    cookTime: "~2 hours",
    ingredients: [
      "1 1/4 cups red split lentils (masoor dal), picked over, washed and drained",
      "5 cups water",
      "1/2 tsp. ground turmeric",
      "5 tbsp. vegetable oil",
      "1 tsp. cumin seeds",
      "2 to 4 cloves garlic, peeled and finely chopped",
      "1 medium onion, peeled and cut into fine slices",
      "1/2 pound cored and finely shredded cabbage",
      "1 to 2 fresh, hot green chilies, finely sliced",
      "1 1/2 tsp. salt",
      "1 medium tomato, peeled and finely chopped",
      "1/2 tsp. peeled, finely grated fresh ginger",
    ],
    directions: [
      "Put the lentils and water into a heavy pot and bring to a boil. Remove any scum that collects at the top. Add the turmeric and stir to mix. Cover, leaving the lid very slightly ajar, turn heat down to low, and simmer gently for 1 1/4 hours. Stir a few times during the last 30 minutes.",
      "When the lentils cook, heat the oil in a 20 to 23 centimeter (8 to 9 inch) frying pan over medium heat. When hot, put in the cumin seeds. Let them sizzle for 3 to 4 seconds. Now put in the garlic. As soon as the garlic pieces begin to brown, put in the onion, cabbage and green chilies. Stir and fry the cabbage mixture for about 10 minutes or until it begins to brown and turn slightly crisp. Stir in 1/4 teaspoon of the salt. Turn off the heat under the frying pan.",
      "When the lentils have cooked for 1 1/4 hours, add the remaining 1 1/4 teaspoon salt, the tomato and ginger to the pot. Stir to mix. Cover and cook another 10 minutes. Add the cabbage mixture and any remaining oil in the frying pan. Stir to mix and bring to a simmer.",
      "Simmer uncovered for 2 to 3 minutes or until the cabbage is heated through.",
    ],
    source: "http://smittenkitchen.com/blog/2007/02/confessions-of-a-cumin-junkie/",
    tags: [
      "indian",
      "spicy",
      "fall",
      "winter",
      "time consuming",
    ],
    home: '/',
  },

  beanPotPie: {
    name: "Bean and Chard Pot Pie",
    servings: "",
    cookTime: "",
    ingredients: [
      "list-group-item-danger:",
      "2 cups all- purpose flour",
      "1/2 tsp. table salt",
      "13 tbsp. cold unsalted butter, diced",
      "6 tbsp. sour cream or whole Greek yogurt",
      "1 tbsp. white wine vinegar",
      "1/4 cup ice water",
      "1 egg, beaten with 1 tbsp. water, for egg wash",
      "FILLING:",
      "2 tbsp. olive oil",
      "1 large or 2 small onions, finely chopped",
      "1 large carrot, finely chopped",
      "1 large stalk celery, finely chopped",
      "Pinch of red pepper flakes",
      "Salt and freshly ground black pepper",
      "2 garlic cloves, minced",
      "4 cups thinly sliced Swiss chard (or kale, or other hearty greens of choice) leaves",
      "3 1/2 tbsp. butter",
      "3 1/2 tbsp. all- purpose flour",
      "3 1/2 cups low- sodium vegetable broth",
      "2 cups white or kidney beans, cooked and drained",
    ],
    directions: [
      "TO MAKE THE LIDS: In a large, wide bowl, combine the flour and salt. Add the butter and, using a pastry blender or your fingertips, cut them up and into the flour mixture until it resembles little pebbles. Keep breaking up the bits of butter until the texture is like uncooked couscous. In a small dish, whisk together the sour cream, vinegar, and water, and combine it with the butter-flour mixture. Using a flexible spatula, stir the wet and the dry together until a craggy dough forms. If needed, get your hands into the bowl to knead it a few times into one big ball. Pat it into a flattish ball, wrap it in plastic wrap, and chill it in the fridge for 1 hour or up to 2 days.",
      "TO MAKE THE FILLING: Heat 1 tablespoon olive oil over medium- high heat in a large, wide saucepan, and then add the pancetta. Brown the pancetta, turning it frequently, so that it colors and crisps on all sides; this takes about 10 minutes. Remove it with a slotted spoon, and drain it on paper towels before transferring to a medium bowl. Leave the heat on and the renderings in the pan. Add an additional tablespoon of olive oil if needed and heat it until it is shimmering. Add onions, carrot, celery, red pepper flakes, and a few pinches of salt, and cook over medium heat until the vegetables are softened and begin to take on color, about 7 to 8 minutes. Add the garlic, and cook for 1 minute more. Add the greens and cook until wilted, about 2 to 3 minutes. Season with the additional salt and freshly ground black pepper to taste. Transfer all of the cooked vegetables to the bowl with the pancetta, and set aside.",
      "For sauce, wipe out the large saucepan; don’t worry if any bits remain stuck to the bottom. Then melt the butter in the saucepan over medium- low heat. Add the flour, and stir with a whisk until combined. Continue cooking for 2 minutes, stirring the whole time, until it begins to take on a little color. Whisk in the broth, one ladleful at a time, mixing completely between additions. Once you’ve added one- third of the broth, you can begin to add the rest more quickly, two to three ladlefuls at a time; at this point you can scrape up any bits that were stuck to the bottom — they’ll add great flavor.",
      "Once all of the broth is added, stirring the whole time, bring the mixture to a boil and reduce it to a simmer. Cook the sauce until it is thickened and gravylike, about 10 minutes. Season with salt and pepper. Stir the white beans and reserved vegetables into the sauce. Preheat your oven to 375 degrees.",
      "Fill a long rectangular pan with filling. Roll out pastry and drape over the edges of the pan. Brush with egg wash and bake until the crust is bronzed and filling is bubbling (about 30 to 35 minutes).",
    ],
    source: "http://smittenkitchen.com/blog/2012/10/pancetta-white-bean-and-swiss-chard-pot-pies/",
    tags: [
      "fall",
      "winter",
      "pie",
      "time consuming",
    ],
    home: '/',
  },

}

// emtpyRecipeObject: {
//   name: "",
//   servings: "",
//   cookTime: "",
//   ingredients: [],
//   directions: [],
//   source: "",
//   tags: [],
//   home: '/',
// }

module.exports = allRecipes;
